[theme]
base="light"
primaryColor="#985d5dff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#d1cfcfff"
textColor="#51575c"

[client]
showSidebarNavigation = true

[browser]
showDevTools = false  # Disables the developer tools

[server]
enableCORS = false